# .graphclientrc.yml
# https://github.com/graphprotocol/graph-client/blob/main/examples/composition/.graphclientrc.yml

sources:
  - name: beefy-clm
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}/latest/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000

  - name: beefy-clm-new
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}/clm/gn
        #endpoint: https://api.goldsky.com/api/public/project_clu70vqkdaz8c010u86i5198g/subgraphs/beefy-clm-{context.chainName:optimism}-tmp-dev/0.0.1/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000

documents:
  - ./src/queries/*.graphql
