# .graphclientrc.yml
# https://github.com/graphprotocol/graph-client/blob/main/examples/composition/.graphclientrc.yml

sources:
  - name: beefy-clm
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}/latest/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: {}

documents:
  - ./src/queries/*.graphql
