# .graphclientrc.yml
# https://github.com/graphprotocol/graph-client/blob/main/examples/composition/.graphclientrc.yml

sources:
  - name: beefy-clm-beta
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}-beta/latest/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000
      - rename:
          mode: wrap
          renames:
            - from:
                type: Query
                field: clmPositions
              to:
                type: Query
                field: beta_clmPositions
            - from:
                type: Query
                field: clm
              to:
                type: Query
                field: beta_clm
            - from:
                type: Query
                field: clms
              to:
                type: Query
                field: beta_clms
            
  - name: beefy-clm-prod
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}/latest/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000

plugins:
  - httpCache:
      matches:
        - 'https://api.goldsky.com'

documents:
  - ./src/queries/*.graphql

additionalTypeDefs: |
  extend type CLM {
    chain: String
  }

additionalResolvers:
  - './src/queries/extensions/chain-resolvers'